### ISSUE TITLE
PDA support

### ISSUE THREAD

**Issue by sanderland** [sanderland/katrain#102]
ref https://www.reddit.com/r/baduk/comments/hfj5sf/how_strong_is_katrain/
Should be tested on the user experience for just having AI PDA to a fixed number.
Alternatively it could do two queries (analysis + ai move query) which doubles computation but gives more flexibility.

**Comment by lightvector** [comment]
Brainstorming a little:

A decent simple formula for PDA to use would be "effective stones of advantage = (komi - 7.5) / 15 + max(0, handicap - 1)", based on the approximation that 1 stone = 15 points, and accounting for the fact that "handicap 2" is really 1, "handicap 3" is really 2, etc, because white goes first... and then starting at 1.5 stones advantage (a traditional 2H game), use PDA = 0, and go up by 0.5 every 1 further stone - so 0.5 for 3H, 1.0 for 4H, etc, capping out at 3.0, achieved at 8H.

For UI, if not wanting to double computation, perhaps a simple indicator that this game is in "handicap mode", a brief tooltip on this indicator that says it improves handicap game strength but also causes estimated scores to _partially_ take into account that black is weaker. And perhaps an opt-in option somewhere to never use handicap mode.

**Comment by sanderland** [comment]
After some consideration I think the best way is a new AI option KataHandicap which has 

* Automatic PDA on/off
* Manual PDA: white+3 to black+3  (player black +3 = player white -3, right?)

Then just have double queries in the AI move. I think PDA in analysis is going to be very weird so I'd rather avoid it.

**Comment by lightvector** [comment]
Right, if it's +3 for one player it's the same as if it's -3 for the other player.

**Comment by sanderland** [comment]
Implemented this as an AI strategy, queries seem to work but I don't notice a lot of differences on 20b, which plays pretty well, but still rather conservative.

**Comment by lightvector** [comment]
PDA definitely matters quite a lot back when I tested it a few months ago, and improved handicap play by about 1 to 1.5 stones in tests against fixed reference opponents (e.g. Leela Classic) and also Friday9i showed that on the *negative* side it improved KataGo's weaker nets from not losing as much to stronger versions of itself. (changes in win chance on the order from 40% to 80% in some configurations, or something like that).

The difference to the actual moves selected is not large in any case, because for the most part, good moves are good moves regardless. Even back then, the way it seemed to matter was the changing of a small number of key moves per game, the choice of where/how deep to invade, a key moment to hane versus extend, or to respond vs tenuki.

But you're right, it hasn't been tested as much with the most recent networks. I wonder if the magnitude of effect has gone down with recent networks (and/or if the recent networks are *also* worse at high handicap games due to this, or not).

Do you notice the reported scores on these queries (even if they aren't being ultimately fed to the displayed stats) being biased by non-zero PDA values? If using a PDA of 3.0 gives a vastly higher winrate to the side who has it positive than if it was at 0, then it's working.

**Comment by sanderland** [comment]
I didn't look at the scores as they're not logged anywhere. I guess I could add them in 'AI thoughts'

**Comment by sanderland** [comment]
Did this which helped fix things, now it noticably plays differently.
