### ISSUE TITLE
Feature Request: QOL Additional settings

### ISSUE THREAD

**Issue by GalaxiousCosmo** [sanderland/katrain#287]
Suggestions:

1. Add options to rebind (or completely remove) default keyboard shortcuts. Example: [Alt] is currently set to open the left slideout menu, which cannot be rebound; the menu constantly opens itself when trying to alt-tab out of KaTrain.
2. Add an option to disable animations for a snappier experience. For example, the ability to disable the animation of the left-menu sliding in and out.
3. Add & move existing tooltips to show on hover only. For example, clicking the engine status colour button to check what it does currently adds a huge text box over the top SGF notes input box, which takes a while to disappear again.
4. Move all of the different menus into one single consolidated menu, with different tabs for the different categories of settings.
5. Move the language options to the consolidated settings menu mentioned in (4).
6. Clear the player names when creating a new game. Currently, the player names for each colour are being filled in automatically when creating a new game.
7. Disable engine evaluation before first move (Or perhaps add an option to enable/disable this)
8. Rearrange the board UI to better make use of the whitespace. See [https://gyazo.com/96755ca55b55ef172f05d6b02ff6a837](https://gyazo.com/96755ca55b55ef172f05d6b02ff6a837) for a proposed layout

Additionally, the popup menu when right-clicking in the node tree for options (such as deleting a branch) takes a while to show; the delay is rather annoying.

**Comment by sanderland** [comment]
1. #296 for the alt-tab thing. No for loads of menus for shortcut config.
2. No
3. There is only one tooltip in the entire program.
4. I prefer being able to directly go to the relevant settings
5. Why?
6. Somewhat fixed by #277 maybe, although the combined use of the menu for new game + edit current game can occasionally make you have to clear them
7. Why?
8. What whitespace? This just suggests a much wider layout

**Comment by GalaxiousCosmo** [comment]
1. Then could at least add an option to remove the default keybindings?
2. Removing animations greatly contributes to snappier user experiences. For example many custom android launchers give the user the option to remove default android OS animations.
3. Why would the number of tooltips be a reason for not making tooltips less intrusive? Currently it covers the SGF note field when the user clicks on it.
4. It's QOL for users, who have different preferences. Currently it looks messy and repetitive, with 5 different menus (including languages) for different settings. I agree that it is slightly faster to have them out, but it is also loads messier.
5. Again, the UI looks very messy
6. So is #277 fixed? If the bug occasionally still shows up, then it's not really fixed, right?
7. Why would the engine have to evaluate an empty board? Maybe it might be interesting to ask the engine, but does it really need to be there always? Hence the suggestion to add a setting to disable it.
8. Full-screen KaTrain and the amount of whitespace should be obvious. My suggestions come from the analysis UI of lichess [https://gyazo.com/41b3559415fe30b102d12ff9b6d19467](https://gyazo.com/41b3559415fe30b102d12ff9b6d19467)

**Comment by sanderland** [comment]
>     1. Then could at least add an option to remove the default keybindings?

It's an open source program, anything is editable for people who really care a lot.

>     2. Removing animations greatly contributes to snappier user experiences. For example many custom android launchers give the user the option to remove default android OS animations.

This is not (yet) an android app, but perhaps such a thing would be relevant then. The animations are largely done by kivymd (https://github.com/kivymd/KivyMD) though.
 
>     3. Why would the number of tooltips be a reason for not making tooltips less intrusive? Currently it covers the SGF note field when the user clicks on it.

Because work vs payoff. I expect the average user to see tooltips less than once in the entire use of the program.
 
>     4. It's QOL for users, who have different preferences.
>     5. Again, the UI looks very messy with all the languages displayed.

Users will always have different preferences, you can't please everyone.
 
>     6. So is #277 fixed? If the bug occasionally still shows up, then it's not really fixed, right?

The bug is fixed. Whether a new game should use the same names or not is another preference depending on usage.
 
>     7. Why would the engine have to evaluate an empty board? Maybe it might be interesting to ask the engine, but does it really need to be there always? Hence the suggestion to add a setting to disable it.

It can't show point loss on move 1 if it doesn't know the score estimate of the empty board and such.
 
>     8. Full-screen KaTrain and the amount of whitespace should be obvious. My suggestions come from the analysis UI of lichess https://gyazo.com/41b3559415fe30b102d12ff9b6d19467

I rarely run it full-screen, often having a discord discussion on half my screen.

**Comment by GalaxiousCosmo** [comment]
Seems like you just don't really care about the user experience aside from your own.
