### ISSUE TITLE
Possibility to resize analysis panel

### ISSUE THREAD

**Issue by 8139david** [sanderland/katrain#301]
The analysis panel on the left is narrow. It would be great if it could be resized freely (at least, freely enlarged).

**Comment by sanderland** [comment]
You mean on the right? Scaling elements and fonts is hard, especially on resizeable things, so it doesn't seem worth it for me.

**Comment by 8139david** [comment]
Yes, I meant on the right.

OK. The "jump to given number" enhancement would already help.

**Comment by 8139david** [comment]
NB: With Sabaki, one can freely resize the information panel, so it's doable.

**Comment by sanderland** [comment]
@8139david please don't argue with my priorities, this is a hobby project in my spare time. I prefer to support features which I find interesting, or support people who want to actively contribute, rather than make settings for every single thing.
One easy option here could be to make it configureable in the theme (see #258) - would that help?

**Comment by sanderland** [comment]
In theme as  RIGHT_PANEL_ASPECT_RATIO = 0.4

![image](https://user-images.githubusercontent.com/48946947/103924120-e995be00-5115-11eb-934e-adb8323c85e9.png)
