### ISSUE TITLE
KaTrain v1.7.6 Error on MacOS catalina

### ISSUE THREAD

**Issue by hrishim** [sanderland/katrain#355]
KaTrain v 1.7.6
OS: macOS Catalina 10.15.7

I just installed KaTrain for macOS (KaTrainOSX.zip) from the releases page. When I open the program I get this error on the pane on the right.

"ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6"

The computer config:
16" MacBookPro 
8-Core Intel i9
16 GB RAM
Graphics: AMD Radeon Pro 5500M 4GB
Intel UHD Graphics 630 1536 MB

When I try General and Engine Settings->Download Models I get more errors like below.

ERROR: Download of 20 block model failed or cancelled ([SSL:CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local certificate (_ssl.c:1125))

This link https://pypi.org/project/KaTrain/INSTALL.md/ (it is supposed to have detailed instructions for MacOS and Windows) gives me a "Page not found".

I tried searching online for solutions but could not find any. The same version of KaTrain installed on Win 10 works ok (I dont have a dedicated GPU so I am using Eigen on windows)

**Comment by sanderland** [comment]
https://github.com/sanderland/katrain/blob/master/INSTALL.md is the install file which mentions the SSL problem.
Not sure what -6 is, and hard to see without console logs.
Have you tried pointing it to a katago installed with 'brew' in general settings?

**Comment by hrishim** [comment]
Thanks for pointing to https://github.com/sanderland/katrain/blob/master/INSTALL.md 
From there I followed another link (https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate) and fixed the SSL certificate problem. So now the models are downloaded. 

But I still get this error on startup:

"ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6"

I did not install katago from brew. I installed KaTrain it from the macOS version on the release page, would that come with Katago or do I need to install that separately?

Does it save/print console logs anywhere ?  Could you point me to the location and I can share the logs

**Comment by sanderland** [comment]
it should come with a katago version that works.
This user found a way to look at logs: https://github.com/sanderland/katrain/issues/331#issuecomment-768956686

**Comment by peepo** [comment]
okay, borrowing a macbook air catalina10.15.7 with Katrain v1.7.6 as mentioned above .dmg installs fine,
and runs once one has open anyway in security, however fails with error -6

will review further tomorrow

**Comment by peepo** [comment]
updated to Big Sur, same result, did not find application logs, tried ~/Library & katrain.app

**Comment by peepo** [comment]
i did not find #331 method to launch from terminal  $  katrain -d
however:
$ /Applications/katrain.app/Contents/MacOS/kivy
/Applications/katrain.app/Contents/Resources/venv/bin /Applications/KaTrain.app/Contents/Resources
/Applications/KaTrain.app/Contents/Resources
objc[2224]: Class SDLApplication is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473db0) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6fdc8). One of the two will be used. Which one is undefined.
objc[2224]: Class SDLAppDelegate is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473e00) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6fe18). One of the two will be used. Which one is undefined.
objc[2224]: Class SDLTranslatorResponder is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473f18) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6fe90). One of the two will be used. Which one is undefined.
objc[2224]: Class SDLMessageBoxPresenter is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473f40) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6feb8). One of the two will be used. Which one is undefined.
objc[2224]: Class SDL_cocoametalview is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473ea0) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6ff08). One of the two will be used. Which one is undefined.
objc[2224]: Class SDLOpenGLContext is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473e50) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6ff58). One of the two will be used. Which one is undefined.
objc[2224]: Class SDLWindow is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473f90) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6ffa8). One of the two will be used. Which one is undefined.
objc[2224]: Class Cocoa_WindowListener is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473fb8) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e6ffd0). One of the two will be used. Which one is undefined.
objc[2224]: Class SDLView is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102474030) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e70048). One of the two will be used. Which one is undefined.
objc[2224]: Class METAL_RenderData is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473d10) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e70098). One of the two will be used. Which one is undefined.
objc[2224]: Class METAL_TextureData is implemented in both /Applications/KaTrain.app/Contents/Frameworks/SDL2.framework/Versions/A/SDL2 (0x102473d60) and /Applications/KaTrain.app/Contents/Resources/venv/lib/python3.8/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x104e700e8). One of the two will be used. Which one is undefined.

Error: engine died unexpectedly without sending output, possibly due to out of memory -6
reported in GUI
