### ISSUE TITLE
Katrain doesn't want to download 1.8.2 katago binaries

### ISSUE THREAD

**Issue by kotenok2000** [sanderland/katrain#418]

**Comment by sanderland** [comment]
which os? windows works for me. i just replaced 1.8.1 with 1.8.2 in the file, so links may be inaccurate. pr appreciated if you want.

**Comment by kotenok2000** [comment]
it said all available binaries already downloaded. i use windows
I redirected i extracted katrain into E:\new folder\neural go\katago-v1.8.1-opencl-windows-x64 and didn't change the directory name.
i also created a symlink to with mklink /j "C:\Users\frolo\.katrain" "E:\new folder\neural go\katago-v1.8.1-opencl-windows-x64"

**Comment by sanderland** [comment]
Ah you're using a released version, 1.8.2 download is only in the 1.9 branch

**Comment by bixbyr** [comment]
From your comment, is this expected behavior that the latest binary release will not download the 1.8.2 katago binary? If so, could we get a new katrain release? I got an email from katago distributed training asking me to update and I'd really prefer to stick with a release instead of python-on-windows-hell.

**Comment by sanderland** [comment]
Is it that hard to point katrain at a downloaded 1.8.2 exe ? Genuinly curious what the confusion is for doing that.
Will see about a release, a bit swamped with a job change/international move in the middle of a global pandemic.

**Comment by kotenok2000** [comment]
I already did it. Should i close the issue?
