### ISSUE TITLE
Feature Request: Showing Territory Diff Between Current and Last Position

### ISSUE THREAD

**Issue by freeradical777** [sanderland/katrain#544]
It may be helpful to show the territory gained/lost as the result of a move, similarly to how lost territory is shown in red in training mode. One way would be to do separate colors for each, such as red (lost) and green (gained).

I have been able to use the territory layer to somewhat judge this, but at times it's very difficult at a glance to tell apart dozens of squares of varying shades of white/grey that are very close together in color. A feature such as this would clearly indicate exactly what territory was lost/gained.

**Comment by sanderland** [comment]
I experimented a bit with this, but I found:

* it is hard to have a good interface/design both in input and output
* the differences often reflect merely what the AI prefers as a next move rather than actual losses, particularly when nothing much happened

Of course, if you work on this and show a convincing use and intuitive design, I can probably integrate it, but be warned that this is not easy.

**Comment by HackYardo** [comment]
Sounds like a A-B-testing. From my poor programming experience, I think it is not hard to implement, just display diff only, and not display A or B, the psesudocode be like this:
```julia
ownershipA = move77.ownership()
ownershipB = move78.ownership()
ownershipDiff = ownershipB - ownershipA
show(ownershipDiff)
```
