### ISSUE TITLE
Default theme should be simple and clean

### ISSUE THREAD

**Issue by milescrawford** [sanderland/katrain#586]
I love that katrain themes are becoming flexible, but I believe the default should be as simple as possible.

The current default errs on the side of exposing _every piece of information available_ as opposed to _helpful simplifications_. This is a common and understandable UI mistake, but it has the effect of overwhelming users as opposed to guiding them.

It is preferable to let advanced users opt in to the additional detail they want to see, as opposed to hoping that newer users will either grok the extreme level of detail or spend the time learning to opt out. This is especially true since opting out requires learning how to create custom json-based themes.

Remember we are all go players! It is most important to have subtle cues to help us understand a board we already know how to read, not a per-point infographic.

The current default display of territory/analysis is like this:
<img src="https://user-images.githubusercontent.com/11055723/205457322-2636b4fe-b6ba-4b21-8979-feadf2b550b3.png" width="500"/>
Shading, marks, transparency, and textured-and-color-coded suggestions are all warring for attention when all we need is a visual cue about ownership.

If "show dots" is on (also the default), it's even wilder, with multiple possible stone marks masking each other:
<img src="https://user-images.githubusercontent.com/11055723/205458467-9d5addbe-2677-4d32-b55f-0ac4ba7ca07e.png" width="500"/>

And the teaching game loss currently proposed is this:
<img src="https://user-images.githubusercontent.com/35696962/205455422-704beb25-68ac-4da1-aedd-080c40aadf64.png" width="500"/>
Details about the quantity of loss per square are being packed into highly-detailed color coding and marks. All we actually need to communicate for a teaching game is "the potential loss is in this area."

I understand that the best simple display is a preference, but I want to see if there is any appetite for pushing things in that direction. If so, I can volunteer to poll and organize some options already supported by Katrain's themes.

**Comment by sanderland** [comment]
I think the purple is going too far and commented as much. The ownership is mostly something to toggle rather than have on all the time, and could hide some marks, but so far the poll in the release is at a whole 7 people care enough to click.
In addition, the complexity is in a large part because people request it. Earlier versions were quite minimalistic.
You're welcome to make a minimalist theme and PR it in, and spread it around though.

**Comment by jacobm-tech** [comment]
We could have a discussion in r/baduk or r/cbaduk. Not everyone is on github. For me, detailed information during shading is helpful: if I want KataGo to analyze the position for me, I want to really understand what it is telling me, including strength of stones (which can be the difference between good and bad). Of course, this is not for the times when I am trying to figure things out for myself - that's what the switches are for.

Of the things you mention, I think that stone transparency is pretty unobtrusive, but I do agree that own-color marks on strong stones are a bit overpowering. My own preference is to have them, for the reasons above, but I understand the people who want weak-stone marks only.

**Comment by milescrawford** [comment]
@sanderland: I think there is some significant selection bias happening here:

> complexity is in a large part because people request it

This is by definition the minority of folks who want to opt-in to greater complexity, so much so that they take steps outside the application to get it. e.g. filing issues on github, creating themes, etc.

> 7 people care enough to click

The poll is in release notes, which is likely only to be read by software engineering types - a demographic that is often biased towards intricate display of information.

Very few of the people who I introduce Katrain to at the go club have a github account, have ever heard of JSON, know how to unzip a theme file into a `~/.katrain` folder, etc. You will never hear from them, they will just think "yuk!" to themselves and never open katrain again. :)

I think @jacobm-tech's idea of putting together a visual poll and soliciting input from r/baduk, OGS forums, KGS chat, etc is a good one, if you want to get a wider option.

But after all, this is your project! So it's important that it stay aligned with your own vision. Thanks for entertaining the conversation in the first place!

**Comment by milescrawford** [comment]
> Of the things you mention, I think that stone transparency is pretty unobtrusive

I think the main problem is that it is showing the same information in multiple ways - stone weakness is already clearly visible in the strength of the shading under the stones. Making them transparent just adds visual noise with the board showing through without displaying any distinct information. I believe this is true of the marks as well.

**Comment by jacobm-tech** [comment]
I don't think redundancy is necessarily a bad thing; in fact, I think that stone transparency works well with shading, because dead and weak stones end up bleached or darkened. The marks are certainly redundant, but I found that the display without them is still not clear enough. Now, if you want the most consistency and no redundancy, the "marks" style is probably best; it is also the most similar to most go-playing programs, including OGS. 

I obviously don't think that my own preferences are the best, but I can tell you that the previous style irked me; yes, you could tell which stones were weak or dead by looking carefully at the shading poking out from under them, so the information was there, but visually, the bright stones were contradicting it; and I saw several comments to that effect.

**Comment by milescrawford** [comment]
Yup, valid opinions. I think both our positions are well stated, and it is up to the taste of the maintainer or the outcome of a poll if we decide to let some discussion set the course.
