### ISSUE TITLE
Window resize and fullscreen issue on Win11

### ISSUE THREAD

**Issue by tomyyd21** [sanderland/katrain#652]
Please read and fill in the appropriate template

# I have a bug report

I'm running Windows 11(22H2) with newest drivers. With KaTrain v1.14.0, it's not possible to set it to full-screen, sometimes even carsh when adjusting the size of the window. I'm wondering if this is a comment issue or spcific promblem in my enviroment?  Of course, if there any additional info required to explain or later fix the problem, I'm more than happy to provide! Thx ;)

**Comment by yocox** [comment]
Get the same problem here.

## Environment
- OS: Win11
- KaTrain: 1.14.0

## How to reproduce
- Method 1
  - Click maximum windows size.
- Method 2
  - Resize window, drag to a large size

## Expected behavior
The window should be resized without problem

## Actually behavior
The window stop response and can only be killed by task manager.

**Comment by neo894** [comment]
try a another screen resolution. it works by me.

**Comment by jojobm** [comment]
what UI language of your katrain. I only reproduce this if I set language =Chinese. eng is fine

**Comment by noahxp** [comment]
Recommend using English language; there is no issue with using English in the English interface.
